services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  upbit-websocket-relay:
    build:
      context: ./upbit-websocket-relay
      dockerfile: Dockerfile
    container_name: upbit_websocket_relay
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      - NODE_ENV=production
    restart: always
